[world]
name = "Skuller"
description = "Custom renderer for Loot Survivor"
cover_uri = "https://raw.githubusercontent.com/rsodre/skuller/refs/heads/main/assets/cover.png"
icon_uri = "https://raw.githubusercontent.com/rsodre/skuller/refs/heads/main/assets/icon.png"
website = "https://github.com/rsodre/skuller"
seed = "skuller"

[world.socials]
x = "https://x.com/matalecode"
# discord = "https://discord.gg/FB2wR6uF"
github = "https://github.com/rsodre/skuller"
# telegram = "https://t.me/dojoengine"

[namespace]
default = "skuller"

[env]
# rpc_url = "https://my.provider.com/starknet/sepolia/rpc" # STARKNET_RPC_URL
# account_address = "" # env: DOJO_ACCOUNT_ADDRESS
# private_key = ""     # env: DOJO_PRIVATE_KEY
world_address = "0x200d01c9f8cffdc13fa0d9aed9b8c5729659b67ee6ad68c6d5fa2e519825bf3"
