kind = "DojoContract"
class_hash = "0x4238753a778a55f7d1e9094a391aa37f59f7db18b8f04c6e8e50c63887b6de9"
original_class_hash = "0x4238753a778a55f7d1e9094a391aa37f59f7db18b8f04c6e8e50c63887b6de9"
base_class_hash = "0x0"
abi = "manifests/mainnet/base/abis/contracts/skuller-main-71f074f3.json"
reads = []
writes = []
init_calldata = []
tag = "skuller-main"
systems = []
manifest_name = "skuller-main-71f074f3"
